language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
 - pip --version 
 # Install current version of nidmresults
 - pip install git+https://github.com/cmaumet/nidmresults.git@nidmresults110#egg=nidmresults
# Install current version of nidmfsl
 - python setup.py install
 # Packages only needed for testing
 - pip install vcrpy
 - pip install ddt
# command to run tests, e.g. python setup.py test
script:  
 - python test/test_install.py  
 - python test/test_fsl_export.py 
 - cat debug.log
# Update subtree nidm from main nidm repository
before_install: 
 - git config --global user.name "TravisCI"
 - git config --global user.email "travis@dummy.com"
 # Create subtree nidm from main nidm repository
 - git remote add nidm https://github.com/cmaumet/nidm.git
 - git fetch nidm
 - git subtree add --prefix nidm nidm/fix_nidmresults_110_gt --squash
 - git subtree add --prefix nidm_releases/1.0.0 nidm tags/NIDM-Results_1.0.0 --squash