language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
 - pip install -r requirements.txt
 # Packages only needed for testing
 - pip install vcrpy
 - pip install ddt
 # Install current version of nidmfsl
 - python nidmresults/setup.py install
 - python setup.py install
# command to run tests, e.g. python setup.py test
script:  python test/test_fsl_export.py 
# Update subtree nidm from main nidm repository
before_install: 
 - git config --global user.name "TravisCI"
 - git config --global user.email "travis@dummy.com"
 # Create subtree nidm from main nidm repository
 - git remote add nidm https://github.com/incf-nidash/nidm.git
 - git fetch nidm
 - git subtree add --prefix nidm nidm/master --squash
 - git subtree add --prefix nidm_releases/1.0.0 nidm tags/NIDM-Results_1.0.0 --squash
# Create subtree nidmresults from main nidmresults repository
 - git remote add nidmresults https://github.com/incf-nidash/nidmresults.git
 - git fetch nidmresults
 - git subtree add --prefix nidmresults nidmresults/master --squash