language: python
# Enable Travis container-based infrastructure
cache:
  pip: true
  directories:
  - test/data/nidmresults-examples
python:
  - "2.7"
  - "3.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 # Install FSL using Neurodebian
 - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
 - sudo apt-get -y update
 - sudo apt-get -y install fsl
 - source /etc/fsl/fsl.sh;
 - export FSLOUTPUTTYPE=NIFTI_GZ
 # Install nidmresults from source in GitHub repo
 - pip install --upgrade --no-deps git+https://github.com/cmaumet/nidmresults.git@no_std_space_coord#egg=nidmresults
 - pip install --upgrade setuptools
 - pip install -r requirements.txt
 - python setup.py install # install nidmfsl from sources
 - curl -sLo - https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz | tar xzvf -
 - export PATH=$PATH:`pwd`/git-lfs-1.1.2
 - cd test/data/nidmresults-examples
 - git lfs install
 - cd ../../..
 - pip --version 
 # Packages only needed for testing (others are set up in requirements.txt)
 - pip install vcrpy
 - pip install ddt
 - pip install gitpython
 - export GIT_PYTHON_TRACE='full'
# command to run tests, e.g. python setup.py test
script:
 # - coverage run --source=nidmfsl -m unittest discover
 - python test/export_test_battery.py
 - python -m unittest discover
 - cat debug.log
# Update subtree nidm from main nidm repository
before_install: 
 - git config --global user.name "TravisCI"
 - git config --global user.email "travis@dummy.com"
# after_success:
#   coveralls