language: python
# Enable Travis container-based infrastructure
sudo: false
cache:
  pip: true
  directories:
  - test/data/nidmresults-examples
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
 - pip install -r requirements.txt
 # install nidmfsl from sources
 - python setup.py install
 - curl -sLo - https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz | tar xzvf -
 - export PATH=$PATH:`pwd`/git-lfs-1.1.2
 - cd test/data/nidmresults-examples
 - git lfs install
 - cd ../../..
 - pip --version 
 # Packages only needed for testing (others are set up in requirements.txt)
 - pip install vcrpy
 - pip install ddt
 - pip install gitpython
 - export GIT_PYTHON_TRACE='full'
# command to run tests, e.g. python setup.py test
script:
 # - coverage run --source=nidmfsl -m unittest discover
 - python test/export_test_battery.py
 - python -m unittest discover
 - cat debug.log
# Update subtree nidm from main nidm repository
before_install: 
 - git config --global user.name "TravisCI"
 - git config --global user.email "travis@dummy.com"
 # Create subtree nidm from main nidm repository
 - git remote add nidm https://github.com/incf-nidash/nidm.git
 - git fetch nidm
 - git fetch nidm --tags
 - git subtree add --prefix nidm nidm/master --squash
 - git subtree add --prefix nidm_releases/1.0.0 nidm tags/NIDM-Results_1.0.0 --squash
 - git subtree add --prefix nidm_releases/1.1.0 nidm tags/NIDM-Results_1.1.0 --squash
 - git subtree add --prefix nidm_releases/1.2.0 nidm tags/NIDM-Results_1.2.0 --squash
# after_success:
#   coveralls